# Die Haupt-KonfigurationsDatei vom "Witchery"-Plugin

# Output ("... ist nun aktiv"/"... ist nun deaktiviert")beim Start und Stopp des Servers deaktivieren
console-output-on-startup-and-end: true
