name: Witchery
main: de.acegames.witchery.Main
authors: [Meisterbetrieb, Laserluffy, TheBozZ_99]
website: http://acegames.de
version: 1.0
description: >
             Ein Zauberhaftes Plugin
commands:
  witchery:
    description: HauptBefehl.
    permission: witchery.main
  witchery-admin:
    description: Admin Befehl.
    permission: witchery.main.admin
permissions:
  witchery.main:
    description: Perm for witchery.
    default: op
